#!/bin/sh
set -e
lb config noauto \
    --mode debian \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --bootappend-live "boot=live components quiet splash" \
    --debian-installer none \
    --firmware-binary false \
    --firmware-chroot false \
    --iso-application "PPSA Installer" \
    --iso-publisher "PPSA; https://github.com/kaiser62/ppsa" \
    --iso-volume "PPSA_INSTALLER" \
    --memtest none \
    --system live \
    "${@}"
